services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:80" # Маппинг хостового порта 8080 на порт 80 внутри контейнера
    depends_on:
      - server
      - microservice
    networks:
      - app-network

  server:
    image: server
    container_name: server
    expose:
      - "8080"
    networks:
      - app-network

  microservice:
    image: microservice
    container_name: microservice
    expose:
      - "8081"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
