name: C++ Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install g++ clang cmake libboost-all-dev
          sudo apt-get install catch2 -y

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Create package
        run: |
          dpkg-deb --build package